version: '3'
services: 
    grafana:
        image: grafana/grafana:7.0.6
        container_name: grafana
        ports: 
        - 3000:3000
    prometheus:
        build: Prometheus
        container_name: prometheus
        ports: 
        - 9090:9090
    node-exporter:
        image: prom/node-exporter:v0.16.0
        container_name: node-exporter
        network_mode: host
        ports: 
        - 9100:9100